<?php
/**
* This class communicates with database
*/

class Database extends PDO
{
    public $db_conn;
    /**
    * [establishes a connection with database]
    * @method __construct
    */
    public function __construct()
    {
        $dsn = 'mysql:host=' . HOST . ';dbname=' . DBNAME;
        $options = array(
        PDO::ATTR_PERSISTENT => true,
        PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION
        );
        $this -> db_conn = new PDO($dsn, USERNAME, PASSWORD, $options);
        if (! isset($this -> db_conn)) {
            echo "error in database connection";
        } else {
            echo "connection to db made <br>";
        }
    }
    /**
    * [runs the query on database]
    * @method return_query_data
    * @param  [String]            $query [Query to be executed]
    * @return [array]                   [results of query]
    */

    public function returnQueryData($query, $flag)
    {
        $table_data_array = array();
        if($flag ==  True) {
            try {
                $response = $this -> db_conn-> query($query);
                while ($row = $response->fetch(\PDO::FETCH_ASSOC)) {
                    array_push($table_data_array, $row);
                }
            } catch (\PDOException $e) {
                echo $e;
            }
            return $table_data_array;
        } else {
            $this -> db_conn-> query($query);
            return null;
        }
    }
    /**
    * [counts the number of results generated by query]
    * @method rowCount
    * @param  [String]   $query [Query to be executed]
    * @return [init]          [Number of records extracted]
    */

    public function rowCount($query)
    {
        $response = $this -> db_conn -> query($query);
        return $response ->rowCount();
    }
}
