<?php
/**
 *
 */
class DBquery
{
    private $table;
    function __construct($table)
    {
        $this ->  table = $table;
    }
    function create($arr)
    {
        // $query = 'INSERT INTO '. $this -> table .'(name,'.'city,'.'email)'. ' VALUES ('. "'". $arr[0] ."'".','. "'".$arr[1] ."'". ','. "'".$arr[2] ."'". ')';
        $query = 'INSERT INTO '. $this -> table . ' VALUES (NULL, ';
        foreach ($arr as &$value) {
            $query =  $query . "'". $value ."',";
        }
        $query = rtrim($query, ",");
        $query = $query . ')';
        // echo $query;
        return $query;
    }
    /**
    * [runs the query on database]
    * @method return_query_data
    * @param  [String]            $query [Query to be executed]
    * @return [array]                   [results of query]
    */

    public function returnQueryData($query, $flag)
    {
        // echo "returnQueryData in DBQuery";
        $table_data_array = array();
        if($flag ==  True) {
            try {
                $response = Database::getInstance()-> db_conn ->  query($query);
                while ($row = $response->fetch(\PDO::FETCH_ASSOC)) {
                    array_push($table_data_array, $row);
                }
            } catch (\PDOException $e) {
                echo $e;
            }
            return $table_data_array;
        } else {
            Database::getInstance()-> db_conn -> query($query);
            return null;
        }
    }
    /**
    * [counts the number of results generated by query]
    * @method rowCount
    * @param  [String]   $query [Query to be executed]
    * @return [init]          [Number of records extracted]
    */

    public function rowCount($query)
    {
        $response = $this -> db_conn -> query($query);
        return $response ->rowCount();
    }
}

?>
